import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import "@/lib/fontawesome";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import NextAuthProvider from "@/Providers/Components/nextauth.providers";
import Providers from "@/Providers/Components/ReactQueryProvider.provider";
import { ToastContainer } from 'react-toastify';
import '@fortawesome/fontawesome-free/css/all.min.css';

const encode = Encode_Sans_Expanded({
  weight: ["300", "400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen">
        <Providers>
          <ToastContainer />

          <NextAuthProvider>
            <div className="">
              <Navbar></Navbar>
            </div>
            <div className="min-h-96 mt-20">
              {children}
            </div>
            <Footer></Footer>
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}
