import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import "./globals.css";
import "@/lib/fontawesome";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import NextAuthProvider from "@/Providers/Components/nextauth.providers";


const encode = Encode_Sans_Expanded({
  weight: ["300", "400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${encode.className} antialiased flex flex-col min-h-screen`}
      >

        <NextAuthProvider>
          <div className="">
            <Navbar></Navbar>
          </div>
          <div >
            {children}
          </div>
          <Footer></Footer>
        </NextAuthProvider>
      </body>
    </html>
  );
}
